### ISSUE TITLE
You need to create sperate file for each program

### ISSUE THREAD

**Issue by ombharamadev** [Arbazkhan-cs/CEIDESIGNCONSULTANCY_WORK#1]
![image](https://github.com/Arbazkhan-cs/CEIDESIGNCONSULTANCY_WORK/assets/150242178/7348b879-2edc-46db-a1cb-249be77ccd80)
You need to create sperate file for each program

**Comment by Arbazkhan-cs** [comment]
Issue Solved
https://github.com/Arbazkhan-cs/CEIDESIGNCONSULTANCY_WORK/tree/main/Day%201

**Comment by ombharamadev** [comment]
ok
