### ISSUE TITLE
in Q7 Day 1 while loop is asking not for loop .... be carefull y

### ISSUE THREAD

**Issue by ombharamadev** [Arbazkhan-cs/CEIDESIGNCONSULTANCY_WORK#3]
![image](https://github.com/Arbazkhan-cs/CEIDESIGNCONSULTANCY_WORK/assets/150242178/672d7f12-f17c-4652-8ef2-64b24012f045)
in Q7 Day 1 while loop is asking not for loop .... be carefully

**Comment by Arbazkhan-cs** [comment]
Issue Solved

**Comment by ombharamadev** [comment]
ok done
![image](https://github.com/Arbazkhan-cs/CEIDESIGNCONSULTANCY_WORK/assets/150242178/9bc42c2b-2616-486c-a269-f6647efc87e0)
